### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VikasRana** [Kagee/audible-downloader#1]
http://s23.postimg.org/buyjghw2j/screenshot_1597.png

Even though book is there in account it is not fetching anything.

**Comment by Kagee** [comment]
Looks like there is a logic fault if the user has only 1 page of books, I'll look into it.

**Comment by Kagee** [comment]
Could you change "maxpage = 0" to "maxpage = 1" on line 318 of download.py, and see if that allows you to download books?

https://github.com/Kagee/audible-downloader/blob/master/download.py#L318

**Comment by Kagee** [comment]
Please pull the latest version of the code, it contains this fix and should work. 

Fixed in de0514008ef297f2efa885cab7c2a2ae04af5995
