### ISSUE TITLE
Enhancement Request: Author folder names for Plex 

### ISSUE THREAD

**Issue by aterriblegamer** [Kagee/audible-downloader#7]
I am running an add-on for Plex that supports Audiobooks. It requires audiobook to be in a folder by author. Then the file is the title of the book.

Would it be possible to update the existing script (or add another script) that would be able to copy the files into folder by author name?

**Comment by aterriblegamer** [comment]
I submitted a change to implement this support. My first GitHub contribution!

**Comment by Kagee** [comment]
I pulled your path into master.
